# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43d8d1ddff8168ba90614b26270d137937aaf2caba9886a88fff751245b3550c0aaad8b3987d5c80fb52a16fbc512f8201b2f3beffe0ff8c1e7724c19dd6501f

test:
  secret_key_base: cea8b9b8a2893bebcf0a779e46bfeb16b6276739f54b337391e137d2c3ec21e45c67fa35d675d1f2404ab704d3c3ab028f34476098c8af7ecea8ea86329a6185

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
